name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Ghostshadowplays
          template: classic
          config_timezone: Europe/London
          filename: metrics.svg

          plugins:
            languages:
              enabled: true
              ignored: [html, css]
              details: [bytes-size, percentage]
              limit: 12

            activity:
              enabled: true

            habits:
              enabled: true

            notable:
              enabled: true

            lines:
              enabled: true

            stars:
              enabled: true
              limit: 6

            repositories:
              enabled: true
              affiliations: owner

            gists:
              enabled: true
